  ███╗   ███╗██╗   ██╗███████╗██╗ ██████╗███████╗██████╗  ██████╗ ███████╗ ██████╗██╗  ██╗███╗   ███╗ ██████╗
  ████╗ ████║██║   ██║██╔════╝██║██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔════╝██╔════╝██║  ██║████╗ ████║██╔════╝
  ██╔████╔██║██║   ██║███████╗██║██║     █████╗  ██████╔╝██║   ██║███████╗██║     ███████║██╔████╔██║██║     
  ██║╚██╔╝██║██║   ██║╚════██║██║██║     ██╔══╝  ██╔══██╗██║   ██║╚════██║██║     ██╔══██║██║╚██╔╝██║██║     
  ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗██║     ██║  ██║╚██████╔╝███████║╚██████╗██║  ██║██║ ╚═╝ ██║╚██████╗
  ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝
Current date and time: Fr 11. Okt 12:03:32 CEST 2024
Current folder: /

|CREATE_Log                                                         241011-12_03_47|
|Work directory: /home/a163/GitRepo/musikfrosch_mc                                 |
|Running script: _main_.py                                                         |
|Spotify token                                                 |nam:Musik|typ: user|
  0%|          | 0/7 [00:00<?, ?it/s] 14%|█▍        | 1/7 [00:00<00:05,  1.02it/s] 29%|██▊       | 2/7 [00:01<00:04,  1.17it/s] 43%|████▎     | 3/7 [00:03<00:04,  1.19s/it] 57%|█████▋    | 4/7 [00:04<00:04,  1.35s/it] 71%|███████▏  | 5/7 [00:39<00:26, 13.26s/it] 86%|████████▌ | 6/7 [00:41<00:09,  9.42s/it] 86%|████████▌ | 6/7 [01:10<00:11, 11.79s/it]
Traceback (most recent call last):
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporärer Fehler bei der Namensauflösung

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7da18bb19c50>: Failed to establish a new connection: [Errno -3] Temporärer Fehler bei der Namensauflösung

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='backstage.eu', port=443): Max retries exceeded with url: /veranstaltungen/live.html?p=7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7da18bb19c50>: Failed to establish a new connection: [Errno -3] Temporärer Fehler bei der Namensauflösung'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a163/GitRepo/musikfrosch_mc/_main_.py", line 57, in <module>
    cd.scrapSideCompare('FroschData_10fin', 'FroschData_01', URLs)
  File "/home/a163/GitRepo/musikfrosch_mc/class_dictionary.py", line 103, in scrapSideCompare
    newEvents = scrapSide(URLs)
                ^^^^^^^^^^^^^^^
  File "/home/a163/GitRepo/musikfrosch_mc/class_dictionary.py", line 82, in scrapSide
    events += scraper()
              ^^^^^^^^^
  File "/home/a163/GitRepo/musikfrosch_mc/scrapers.py", line 477, in backstage
    r = requests.get(f"{URL}?p={i}")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='backstage.eu', port=443): Max retries exceeded with url: /veranstaltungen/live.html?p=7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7da18bb19c50>: Failed to establish a new connection: [Errno -3] Temporärer Fehler bei der Namensauflösung'))
