  ███╗   ███╗██╗   ██╗███████╗██╗ ██████╗███████╗██████╗  ██████╗ ███████╗ ██████╗██╗  ██╗███╗   ███╗ ██████╗
  ████╗ ████║██║   ██║██╔════╝██║██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔════╝██╔════╝██║  ██║████╗ ████║██╔════╝
  ██╔████╔██║██║   ██║███████╗██║██║     █████╗  ██████╔╝██║   ██║███████╗██║     ███████║██╔████╔██║██║     
  ██║╚██╔╝██║██║   ██║╚════██║██║██║     ██╔══╝  ██╔══██╗██║   ██║╚════██║██║     ██╔══██║██║╚██╔╝██║██║     
  ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗██║     ██║  ██║╚██████╔╝███████║╚██████╗██║  ██║██║ ╚═╝ ██║╚██████╗
  ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝
Current date and time: So 29. Sep 18:26:37 CEST 2024
Current folder: /

Traceback (most recent call last):
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/spotipy/oauth2.py", line 588, in refresh_access_token
    response.raise_for_status()
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a163/GitRepo/musikfrosch_mc/_main_.py", line 25, in <module>
    import scrapers as s
  File "/home/a163/GitRepo/musikfrosch_mc/scrapers.py", line 17, in <module>
    import class_dictionary as cd
  File "/home/a163/GitRepo/musikfrosch_mc/class_dictionary.py", line 23, in <module>
    SP_a163 = spot.spotfy_class(a163_LOGIN, SCOPE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/GitRepo/musikfrosch_mc/spotypys.py", line 54, in __init__
    token = util.prompt_for_user_token(username=SP_LOGIN[0],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/spotipy/util.py", line 96, in prompt_for_user_token
    token_info = sp_oauth.validate_token(sp_oauth.cache_handler.get_cached_token())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/spotipy/oauth2.py", line 380, in validate_token
    token_info = self.refresh_access_token(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/spotipy/oauth2.py", line 596, in refresh_access_token
    self._handle_oauth_error(http_error)
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/spotipy/oauth2.py", line 146, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: temporarily_unavailable, error_description: 
